name = "Bgen"
uuid = "6db4b851-9beb-4b83-9d64-eb1cfb37721d"
authors = ["Seyoon Ko <syko0507@snu.ac.kr> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
